<div class="sharethis-inline-share-buttons st-right  st-inline-share-buttons st-animated" id="st-1">
    <div class="st-btn facebook" data-network="facebook" >
        <i class="fa fa-facebook" aria-hidden="true"></i>
    </div>
    <div class="st-btn twitter" data-network="twitter" >
        <i class="fa fa-twitter" aria-hidden="true"></i>
    </div>
    <div class="st-btn pinterest" data-network="pinterest">
        <i class="fa fa-pinterest" aria-hidden="true"></i>
    </div>
    <div class="st-btn email" data-network="email">
        <i class="fa fa-envelope" aria-hidden="true"></i>
    </div>
    <div class="st-btn sharethis" data-network="sharethis">
        <i class="fa fa-share-alt" aria-hidden="true"></i>
    </div>
</div>
